---
- name: Ensure Aegir's dependencies are installed.
  apt:
    name: "{{ item }}"
    state: installed
  when: (aegir_cluster_node_manage_dependencies == true) and (ansible_os_family == 'Debian')
  with_items: aegir_cluster_node_dependencies

- name: Install additional packages.
  apt:
    name: "{{ item }}"
    state: installed
  when: (aegir_cluster_node_install_additional_packages == true) and (ansible_os_family == 'Debian')
  with_items: aegir_cluster_node_additional_packages

# Ref.: http://community.aegirproject.org/installing/manual#Create_the_Aegir_user
- name: Create 'aegir' group
  group:
    name: "{{ aegir_cluster_node_user }}"
    system: yes
- name: Create 'aegir' user
  user:
    name: "{{ aegir_cluster_node_user }}"
    system: yes
    home: "{{ aegir_cluster_node_root }}"
    group: "{{ aegir_cluster_node_user }}"
    groups: "{{ aegir_cluster_node_web_group }}"
    append: yes

# Ref.: http://community.aegirproject.org/installing/manual#Install_provision
- name: Create 'aegir' user home.
  file:
    path: "{{ aegir_cluster_node_root }}"
    state: directory
    owner: "{{ aegir_cluster_node_user }}"
    group: "{{ aegir_cluster_node_user }}"

# Ref.: http://community.aegirproject.org/installing/manual#Apache_configuration
- include: setup-apache.yml
  when: aegir_cluster_node_http_service_type == 'apache'

# Ref.: http://community.aegirproject.org/installing/manual#Sudo_configuration
- name: Configure sudo for aegir user
  copy:
    dest: "/etc/sudoers.d/{{ aegir_cluster_node_user }}"
    content: "{{ aegir_cluster_node_user }} ALL=NOPASSWD: /usr/sbin/apache2ctl\n{{ aegir_cluster_node_user }} ALL=NOPASSWD: /etc/init.d/nginx\n\n"
    mode: 0440

- include: grant-ssh-access.yml
  when: aegir_cluster_node_grant_ssh_access
